#gege upload

no_metadata = true
async_upload = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = false
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
gradient_checkpointing = false
low_vram = false

###### huggingface ######
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""

max_bucket_reso = 2048
max_data_loader_n_workers = 8
max_grad_norm = 1
max_token_length = 225
min_bucket_reso = 256
mixed_precision = "bf16"
no_half_vae = true
output_dir = "runs/sdxl_multi_style"
output_name = "sdxl_multi_style_lora"
pretrained_model_name_or_path = ""
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_model_as = "safetensors"
save_precision = "bf16"
full_fp16 = false
train_data_dir = "img"
training_comment = ""
xformers = true

###### steps and epochs ######
max_train_epochs = 30
save_every_n_epochs = 5

###### loss function ######
loss_type = "l2"

###### batch size ######
train_batch_size = 12
gradient_accumulation_steps = 1

###### optimizer ######
optimizer_type = "AdamW8bit"
optimizer_args = [ "betas=(0.9, 0.999)", "weight_decay=0.01", "eps=1e-08",]
unet_lr = 0.000008
text_encoder_lr = 0.000006

###### lr scheduler ######
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 150

###### noise offset ######
noise_offset_type = "Original"
noise_offset = 0.0324
#noise_offset_type = "Multires"
#multires_noise_iterations = 6
#multires_noise_discount = 0.3

###### misc ######
network_alpha = 256
network_dim = 256
network_module = "networks.lora"
network_args = []
network_dropout = 0.02
caption_dropout_rate = 0.05
clip_skip = 1
max_timestep = 1000
min_snr_gamma = 5
scale_weight_norms = 5
seed = 2951032222
